Traceback (most recent call last):
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/hidde/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
qe_dic = {
            '&CONTROL': {
                'pseudo_dir': '/home/hidde/hidde/Unige/dft/pseudo/'
            },
            '&SYSTEM': {
                'occupations': 'smearing',
                'smearing': 'mv',
                'degauss': 0.015,  
                'ecutwfc': 45,
                'ecutrho': 180,
                'nbnd': 30
            }
        }
w90_dic = {
    'num_wann': 2,
    'num_bands': 30,
    'num_iter': 2000
}

atoms = {
    'C': {'weight': 12.0107,
         'pseudo_potential': 'C.pbe-n-kjpaw_psl.1.0.0.UPF',
         'loc': [np.array([0, 0, 0]), np.array([0, 1.42, 0])],
          'projections': ['pz'],
          'color': 'grey'
    }
}

data_dir = '../'*3 + 'dft_data'
graphene = moire.dft.W90(w90_dic, qe_dic, "/home/hidde/hidde/Unige/dft/graphene", 'graphene', 
           [np.array([2.45951214, 0, 0]), np.array([-1.2297560, 2.130000, 0])], data_dir=data_dir)
graphene.set_atoms(atoms)
graphene.set_k_grid(8)
graphene.set_k_path([(0, 0, 0), (0.5, 0, 0), (1/3, 1/3, 0), (0, 0, 0)], ["Î“", "M", "K", "Î“"], 100)
graphene.set_window(-12, 8, -4.3, -4.1, 500)
------------------

[0;31m--------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-2-b79823baec1b>[0m in [0;36m<module>[0;34m[0m
[1;32m     28[0m [0;34m[0m[0m
[1;32m     29[0m [0mdata_dir[0m [0;34m=[0m [0;34m'../'[0m[0;34m*[0m[0;36m3[0m [0;34m+[0m [0;34m'dft_data'[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 30[0;31m graphene = moire.dft.W90(w90_dic, qe_dic, "/home/hidde/hidde/Unige/dft/graphene", 'graphene', 
[0m[1;32m     31[0m            [np.array([2.45951214, 0, 0]), np.array([-1.2297560, 2.130000, 0])], data_dir=data_dir)
[1;32m     32[0m [0mgraphene[0m[0;34m.[0m[0mset_atoms[0m[0;34m([0m[0matoms[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'moire' has no attribute 'dft'
AttributeError: module 'moire' has no attribute 'dft'

