Traceback (most recent call last):
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/hidde/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/hidde/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
qe_dic = {
            '&CONTROL': {
                'pseudo_dir': '/home/hidde/hidde/Unige/dft/pseudo/'
            },
            '&SYSTEM': {
                'occupations': 'smearing',
                'smearing': 'mv',
                'degauss': 0.015,  
                'ecutwfc': 45,
                'ecutrho': 180,
                'nbnd': 30
            }
        }

graphene_lat = Lattice(2.45951214)
C_dic = dict(name='C', color='blue', draw_radius=50, pseudo_potential='C.pbe-n-kjpaw_psl.1.0.0.UPF', weight=12.0107)
graphene_lat.set_atom(np.array((0, 0, 0)), C_dic)
graphene_lat.set_atom(np.array([0, 1.42, 0]), C_dic)

data_dir = '/home/hidde/hidde/Unige/dft/graphene'
graphene = DFT('graphene', data_dir, data_dir)
graphene.prepare_qe(qe_dic)
graphene.import_lattice(my_lat)
graphene.set_k_grid(8)
graphene.set_k_path([(0, 0, 0), (0.5, 0, 0), (1/3, 1/3, 0), (0, 0, 0)], ["Î“", "M", "K", "Î“"], 100)

graphene.plot_bands(dis_min=-6, dis_max=-4, Î±=0.3)
w90_dic = {
    'num_wann': 2,
    'num_bands': 30,
    'num_iter': 2000
}

atoms = {
    'C': {'weight': 12.0107,
         'pseudo_potential': 'C.pbe-n-kjpaw_psl.1.0.0.UPF',
         'loc': [np.array([0, 0, 0]), np.array([0, 1.42, 0])],
          'projections': ['pz'],
          'color': 'grey'
    }
}

data_dir = '../'*3 + 'dft_data'
graphene = moire.dft.W90(w90_dic, qe_dic, "/home/hidde/hidde/Unige/dft/graphene", 'graphene', 
           [np.array([2.45951214, 0, 0]), np.array([-1.2297560, 2.130000, 0])], data_dir=data_dir)
graphene.set_atoms(atoms)
graphene.set_k_grid(8)
graphene.set_k_path([(0, 0, 0), (0.5, 0, 0), (1/3, 1/3, 0), (0, 0, 0)], ["Î“", "M", "K", "Î“"], 100)
graphene.set_window(-12, 8, -4.3, -4.1, 500)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-1fbe3d0e84cb>[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0mgraphene[0m [0;34m=[0m [0mDFT[0m[0;34m([0m[0;34m'graphene'[0m[0;34m,[0m [0mdata_dir[0m[0;34m,[0m [0mdata_dir[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m [0mgraphene[0m[0;34m.[0m[0mprepare_qe[0m[0;34m([0m[0mqe_dic[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m [0mgraphene[0m[0;34m.[0m[0mimport_lattice[0m[0;34m([0m[0mmy_lat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     24[0m [0mgraphene[0m[0;34m.[0m[0mset_k_grid[0m[0;34m([0m[0;36m8[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     25[0m [0mgraphene[0m[0;34m.[0m[0mset_k_path[0m[0;34m([0m[0;34m[[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m)[0m[0;34m,[0m [0;34m([0m[0;36m0.5[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m)[0m[0;34m,[0m [0;34m([0m[0;36m1[0m[0;34m/[0m[0;36m3[0m[0;34m,[0m [0;36m1[0m[0;34m/[0m[0;36m3[0m[0;34m,[0m [0;36m0[0m[0;34m)[0m[0;34m,[0m [0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m)[0m[0;34m][0m[0;34m,[0m [0;34m[[0m[0;34m"Î“"[0m[0;34m,[0m [0;34m"M"[0m[0;34m,[0m [0;34m"K"[0m[0;34m,[0m [0;34m"Î“"[0m[0;34m][0m[0;34m,[0m [0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'my_lat' is not defined
NameError: name 'my_lat' is not defined

